services:
  - type: web
    name: easy-ocr-flask
    env: python
    buildCommand: |
      apt-get update && \
      apt-get install -y tesseract-ocr tesseract-ocr-hin tesseract-ocr-eng && \
      pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: FLASK_ENV
        value: production
    healthCheckPath: /health